### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by YorgosKs** [YorgosKs/metadev#1]
- **Home page (/)**
- [x]  Design and develop 

- **Dashboard page(/dashboard)**
- [x] Pie chart for employees
- [x] Limit current positions to 3 and link them with id to /open-positions
- [x] Possibly redesign (a bit) numbers in cards
- [x] Get status of employees for pie chart card

- **Protected routes**
- [x] Prevent go to public routes

- **Employees page(/employees)**
- [x] Possibly redesign rows (a bit)

- **General fixes**
- [ ] A bit of responsiveness 
- [ ]
